apiVersion: v1
kind: Service
metadata:
  name: message-app-express-service
spec:
  selector:
    app: message-app-express
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
