apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-app-express
  labels:
    app: message-app-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-app-express
  template:
    metadata:
      labels:
        app: message-app-express
    spec:
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
            - name: MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: database_url
